/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Beans.CadastroAtendimentosBeans;
import Beans.CadastroClientesBeans;
import Beans.CadastroColaboradoresBeans;
import Beans.CadastroServicosBeans;
import DAO.CadastroAtendimentosDAO;
import DAO.CadastroClientesDAO;
import DAO.CadastroColaboradoresDAO;
import DAO.CadastroServicosDAO;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class Atendimentos extends javax.swing.JInternalFrame {

    ArrayList<CadastroServicosBeans> listaServicos;
    ArrayList<CadastroClientesBeans> listaClientes;
    ArrayList<CadastroColaboradoresBeans> listaColaboradores;
    ArrayList<CadastroAtendimentosBeans> listaAtendimentos;

    DefaultComboBoxModel<CadastroServicosBeans> modelServicos;
    DefaultComboBoxModel<CadastroClientesBeans> modelClientes;
    DefaultComboBoxModel<CadastroColaboradoresBeans> modelColaboradores;

    DefaultTableModel modelAtendimentos;

    /**
     * Creates new form Servicos
     */
    public Atendimentos() throws SQLException {
        
        listaServicos = CadastroServicosDAO.listaServicos();
        listaClientes = CadastroClientesDAO.listaClientes();
        listaColaboradores = CadastroColaboradoresDAO.listaColaboradores();
        
        modelServicos = new DefaultComboBoxModel<>();
        for (CadastroServicosBeans servico : listaServicos) {
            modelServicos.addElement(servico);
        }
        modelClientes = new DefaultComboBoxModel<>();
        for (CadastroClientesBeans clientes : listaClientes) {
            modelClientes.addElement(clientes);
        }
        modelColaboradores = new DefaultComboBoxModel<>();
        for (CadastroColaboradoresBeans colaboradores : listaColaboradores) {
            modelColaboradores.addElement(colaboradores);
        }

        listaAtendimentos = CadastroAtendimentosDAO.listaAtendimentos();

        modelAtendimentos = new DefaultTableModel(new String[]{
            "Código", "Nome Serviço", "Nome Cliente", "Nome Colaborador", "Data Atendimento"
        }, 0);

        for (CadastroAtendimentosBeans atendimento : listaAtendimentos) {
            String nomeServico = "";
            String nomeCliente = "";
            String nomeColaborador = "";
            for (CadastroServicosBeans servico: listaServicos){
                if (servico.getIdServico() == atendimento.getIdServico()){
                    nomeServico = servico.getNome();
                    break;
                }
            }
            
            for (CadastroClientesBeans cliente: listaClientes){
                if (cliente.getIdClientes() == atendimento.getIdClientes()){
                    nomeCliente = cliente.getNomeClientes();
                    break;
                }
            }
            
            for (CadastroColaboradoresBeans colaborador: listaColaboradores){
                if (colaborador.getIdColaboradores()== atendimento.getIdColaboradores()){
                    nomeColaborador = colaborador.getNomeColaboradores();
                    break;
                }
            }
            
            Object[] linha = {
                atendimento.getIdAtendimentos(),
                nomeServico,
                nomeCliente,
                nomeColaborador,
                atendimento.getDataAtendimentos()
            }; 
            modelAtendimentos.addRow(linha);
        }

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPrincipalAtendimentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfCodigoAtendimentos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbLimpar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        cbxServico = new javax.swing.JComboBox();
        cbxCliente = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbxColaborador = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tfDataAtendimento = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Cadastro de Atendimentos");

        tabelaPrincipalAtendimentos.setBackground(new java.awt.Color(255, 204, 255));
        tabelaPrincipalAtendimentos.setModel(modelAtendimentos);
        tabelaPrincipalAtendimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPrincipalAtendimentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPrincipalAtendimentos);

        jLabel1.setText("Código");

        jtfCodigoAtendimentos.setBackground(new java.awt.Color(255, 204, 255));
        jtfCodigoAtendimentos.setForeground(new java.awt.Color(255, 204, 255));
        jtfCodigoAtendimentos.setToolTipText("");
        jtfCodigoAtendimentos.setEnabled(false);
        jtfCodigoAtendimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoAtendimentosActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome Serviço");

        jLabel3.setText("Cliente");

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/8686254_ic_fluent_text_clear_formatting_icon.png"))); // NOI18N
        jbLimpar.setToolTipText("Limpar");
        jbLimpar.setBorderPainted(false);
        jbLimpar.setContentAreaFilled(false);
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/2639912_save_icon.png"))); // NOI18N
        jbSalvar.setToolTipText("Salvar");
        jbSalvar.setBorderPainted(false);
        jbSalvar.setContentAreaFilled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/2638315_bin_delete_dust_erace_garbage_icon.png"))); // NOI18N
        jbDeletar.setToolTipText("Excluir");
        jbDeletar.setBorderPainted(false);
        jbDeletar.setContentAreaFilled(false);
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/353430_checkbox_pen_edit_pencil_icon.png"))); // NOI18N
        jbEditar.setToolTipText("Editar");
        jbEditar.setBorderPainted(false);
        jbEditar.setContentAreaFilled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        cbxServico.setModel((ComboBoxModel<CadastroServicosBeans>) modelServicos);
        cbxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxServicoActionPerformed(evt);
            }
        });

        cbxCliente.setModel((ComboBoxModel<CadastroClientesBeans>) modelClientes);

        jLabel4.setText("Data Atendimento");

        cbxColaborador.setModel((ComboBoxModel<CadastroColaboradoresBeans>) modelColaboradores);
        cbxColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxColaboradorActionPerformed(evt);
            }
        });

        jLabel5.setText("Colaborador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDataAtendimento))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(6, 6, 6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCodigoAtendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxServico, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbDeletar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbSalvar)
                                .addGap(48, 48, 48)
                                .addComponent(jbEditar)))
                        .addGap(96, 96, 96)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfCodigoAtendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbSalvar)
                            .addComponent(jbEditar))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbLimpar)
                            .addComponent(jbDeletar))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDataAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodigoAtendimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoAtendimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoAtendimentosActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        CadastroServicosDAO tipoPagamento = new CadastroServicosDAO();
        //esse objeto pega os métodos gets e sets
        CadastroServicosBeans excluir = new CadastroServicosBeans();

        excluir.setIdServico(Integer.parseInt(jtfCodigoAtendimentos.getText()));

        try {
            tipoPagamento.excluir(excluir);
        } catch (SQLException ex) {
            Logger.getLogger(Atendimentos.class.getName()).log(Level.SEVERE, null, ex);
        }

        limpaCampos();

        try {
            CadastroServicosDAO.listaServicos();
        } catch (SQLException ex) {
            Logger.getLogger(Atendimentos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        //esse objeto referencia a classe onde irá salvar
        CadastroServicosDAO cadServicos = new CadastroServicosDAO();
        //esse objeto pega os métodos gets e sets
        CadastroServicosBeans cadastro = new CadastroServicosBeans();

        try {
            cadServicos.Cadastrar(cadastro);
        } catch (SQLException ex) {
            Logger.getLogger(Atendimentos.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(this, "Serviço cadastrado com sucesso!",
                "Cadastro de Serviço", //Cria caixa de texto após executada a ação.
                JOptionPane.INFORMATION_MESSAGE); //vai pegar, tratar a exception.
        limpaCampos();


    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpaCampos();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void tabelaPrincipalAtendimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPrincipalAtendimentosMouseClicked

    }//GEN-LAST:event_tabelaPrincipalAtendimentosMouseClicked

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        CadastroServicosDAO servico = new CadastroServicosDAO();
        CadastroServicosBeans editar = new CadastroServicosBeans();

        editar.setIdServico(Integer.parseInt(jtfCodigoAtendimentos.getText()));

        try {
            servico.alterar(editar);
        } catch (SQLException ex) {
            Logger.getLogger(Atendimentos.class.getName()).log(Level.SEVERE, null, ex);
        }

        limpaCampos();

        try {
            CadastroServicosDAO.listaServicos();
        } catch (SQLException ex) {
            Logger.getLogger(Atendimentos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jbEditarActionPerformed

    private void cbxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxServicoActionPerformed


    }//GEN-LAST:event_cbxServicoActionPerformed

    private void cbxColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxColaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxColaboradorActionPerformed

    public void limpaCampos() {
        jtfCodigoAtendimentos.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxCliente;
    public static javax.swing.JComboBox cbxColaborador;
    private javax.swing.JComboBox cbxServico;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvar;
    public static javax.swing.JTextField jtfCodigoAtendimentos;
    public static javax.swing.JTable tabelaPrincipalAtendimentos;
    private javax.swing.JTextField tfDataAtendimento;
    // End of variables declaration//GEN-END:variables
}
