/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Beans.CadastroAtendimentosBeans;
import Beans.CadastroServicosBeans;
import DAO.CadastroAtendimentosDAO;
import DAO.CadastroServicosDAO;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class relatorioAtendimentos extends javax.swing.JInternalFrame {

    ArrayList<CadastroServicosBeans> listaServicos;
    ArrayList<CadastroAtendimentosBeans> listaAtendimentos;

    DefaultComboBoxModel<CadastroServicosBeans> modelServicos;

    DefaultTableModel modelAtendimentos;

    /**
     * Creates new form Servicos
     */
    public relatorioAtendimentos() throws SQLException {
        listaServicos = CadastroServicosDAO.listaServicos();
        modelServicos = new DefaultComboBoxModel<>();
        for (CadastroServicosBeans servico : listaServicos) {
            modelServicos.addElement(servico);
        }

        listaAtendimentos = CadastroAtendimentosDAO.listaAtendimentos();

        modelAtendimentos = new DefaultTableModel(new String[]{
            "Código", "Nome Serviço", "Nome Cliente", "Nome Colaborador", "Data Atendimento"
        }, 0);

        for (CadastroAtendimentosBeans atendimento : listaAtendimentos) {
            String nomeServico = "";
            for (CadastroServicosBeans servico: listaServicos){
                if (servico.getIdServico() == atendimento.getIdServico()){
                    nomeServico = servico.getNome();
                    break;
                }
            }
            
            Object[] linha = {
                atendimento.getIdAtendimentos(),
                nomeServico,
                atendimento.getIdClientes(),
                atendimento.getIdColaboradores(),
                atendimento.getDataAtendimentos()
            }; 
            modelAtendimentos.addRow(linha);
        }

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPrincipalrelatorioAtendimentos = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Relatório de Atendimentos");

        tabelaPrincipalrelatorioAtendimentos.setBackground(new java.awt.Color(255, 204, 255));
        tabelaPrincipalrelatorioAtendimentos.setModel(modelAtendimentos);
        tabelaPrincipalrelatorioAtendimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPrincipalrelatorioAtendimentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPrincipalrelatorioAtendimentos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaPrincipalrelatorioAtendimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPrincipalrelatorioAtendimentosMouseClicked

    }//GEN-LAST:event_tabelaPrincipalrelatorioAtendimentosMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabelaPrincipalrelatorioAtendimentos;
    // End of variables declaration//GEN-END:variables
}
