/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.AtendimentoController;
import controller.ClienteController;
import controller.ColaboradorController;
import controller.ServicoController;
import models.Atendimento;
import models.Servico;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import models.Cliente;
import models.Colaborador;

/**
 *
 * @author Victor
 */
public class TelaRelatorioAtendimentos extends javax.swing.JInternalFrame {

    private AtendimentoController atendimentoController;
    private ServicoController servicoController;
    private ClienteController clienteController;
    private ColaboradorController colaboradorController;

    /**
     * Creates new form Servicos
     */
    public TelaRelatorioAtendimentos() throws SQLException {
        initComponents();
        
        // Inicializa controllers
        atendimentoController = new AtendimentoController();
        servicoController = new ServicoController();
        clienteController = new ClienteController();
        colaboradorController = new ColaboradorController();
        
        atualizarRelatorio();
    }

    private void atualizarRelatorio() throws SQLException {
        List<Atendimento> atendimentos = atendimentoController.listarTodos();
        
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"Código", "Nome Serviço", "Cliente", "Colaborador", "Data Atendimento"}, 0
        );

        for (Atendimento atendimento : atendimentos) {
            String nomeServico = obterNomeServico(atendimento.getIdServico());
            String nomeCliente = obterNomeCliente(atendimento.getIdClientes());
            String nomeColaborador = obterNomeColaborador(atendimento.getIdColaboradores());
            
            model.addRow(new Object[]{
                atendimento.getIdAtendimentos(),
                nomeServico,
                nomeCliente,
                nomeColaborador,
                atendimento.getDataAtendimentos()
            });
        }
        
        tabelaPrincipalrelatorioAtendimentos.setModel(model);
    }
    
    private String obterNomeServico(int idServico) throws SQLException {
        List<Servico> servicos = servicoController.listarTodos();
        for (Servico servico : servicos) {
            if (servico.getIdServico() == idServico) {
                return servico.getNome();
            }
        }
        return "Serviço não encontrado";
    }
    
    private String obterNomeCliente(int idCliente) throws SQLException {
        List<Cliente> clientes = clienteController.listarTodos();
        for (Cliente cliente : clientes) {
            if (cliente.getIdCliente() == idCliente) {
                return cliente.getNome();
            }
        }
        return "Cliente não encontrado";
    }
    
    private String obterNomeColaborador(int idColaborador) throws SQLException {
        List<Colaborador> colaboradores = colaboradorController.listarTodos();
        for (Colaborador colaborador : colaboradores) {
            if (colaborador.getIdColaboradores() == idColaborador) {
                return colaborador.getNome();
            }
        }
        return "Colaborador não encontrado";
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPrincipalrelatorioAtendimentos = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Relatório de Atendimentos");

        tabelaPrincipalrelatorioAtendimentos.setBackground(new java.awt.Color(255, 204, 255));
        tabelaPrincipalrelatorioAtendimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaPrincipalrelatorioAtendimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPrincipalrelatorioAtendimentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPrincipalrelatorioAtendimentos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaPrincipalrelatorioAtendimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPrincipalrelatorioAtendimentosMouseClicked

    }//GEN-LAST:event_tabelaPrincipalrelatorioAtendimentosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabelaPrincipalrelatorioAtendimentos;
    // End of variables declaration//GEN-END:variables
}
