/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import models.Colaborador;
import models.Servico;
import dao.ColaboradorDAO;
import dao.ServicoDAO;
import tabela.Tabela;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Victor
 */
public class TelaColaboradores extends javax.swing.JInternalFrame {

    /**
     * Creates new form Servicos
     */
    public TelaColaboradores() throws SQLException {
        initComponents();
        atualizarTabela();
            
            
            
    }
    
    private void atualizarTabela() throws SQLException{
        Tabela modelo = ColaboradorDAO.obterTabela();
        
        tabelaPrincipalColaboradores.setModel(modelo);
        tabelaPrincipalColaboradores.getColumnModel().getColumn(0).setPreferredWidth(1);
        tabelaPrincipalColaboradores.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelaPrincipalColaboradores.getColumnModel().getColumn(2).setPreferredWidth(200);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPrincipalColaboradores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfCodigoColaboradores = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfNomeColaboradores = new javax.swing.JTextField();
        jtfTelefoneColaboradores = new javax.swing.JTextField();
        jbLimpar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Cadastro de Colaboradores");

        tabelaPrincipalColaboradores.setBackground(new java.awt.Color(255, 204, 255));
        tabelaPrincipalColaboradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome Colaborador", "Telefone Colaborador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPrincipalColaboradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPrincipalColaboradoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPrincipalColaboradores);

        jLabel1.setText("Código");

        jtfCodigoColaboradores.setBackground(new java.awt.Color(255, 204, 255));
        jtfCodigoColaboradores.setForeground(new java.awt.Color(255, 204, 255));
        jtfCodigoColaboradores.setToolTipText("");
        jtfCodigoColaboradores.setEnabled(false);
        jtfCodigoColaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoColaboradoresActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome Colaborador");

        jLabel3.setText("Telefone Colaborador");

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/8686254_ic_fluent_text_clear_formatting_icon.png"))); // NOI18N
        jbLimpar.setToolTipText("Limpar");
        jbLimpar.setBorderPainted(false);
        jbLimpar.setContentAreaFilled(false);
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/2639912_save_icon.png"))); // NOI18N
        jbSalvar.setToolTipText("Salvar");
        jbSalvar.setBorderPainted(false);
        jbSalvar.setContentAreaFilled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/2638315_bin_delete_dust_erace_garbage_icon.png"))); // NOI18N
        jbDeletar.setToolTipText("Excluir");
        jbDeletar.setBorderPainted(false);
        jbDeletar.setContentAreaFilled(false);
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/353430_checkbox_pen_edit_pencil_icon.png"))); // NOI18N
        jbEditar.setToolTipText("Editar");
        jbEditar.setBorderPainted(false);
        jbEditar.setContentAreaFilled(false);
        jbEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbEditarMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbEditarMouseReleased(evt);
            }
        });
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNomeColaboradores, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(jtfTelefoneColaboradores)
                            .addComponent(jtfCodigoColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbDeletar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbSalvar)
                                .addGap(48, 48, 48)
                                .addComponent(jbEditar)))
                        .addGap(96, 96, 96)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfCodigoColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfNomeColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfTelefoneColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbSalvar)
                            .addComponent(jbEditar))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbLimpar)
                            .addComponent(jbDeletar))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodigoColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoColaboradoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoColaboradoresActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        ColaboradorDAO tipoColaboradores = new ColaboradorDAO();
        //esse objeto pega os métodos gets e sets
        Colaborador excluir = new Colaborador();
        
               //obter a partir da tabela qual o objeto selecionado 
        
        int linha = tabelaPrincipalColaboradores.getSelectedRow();
        if(linha < 0 )
            return;
        
        int id = Integer.parseInt(tabelaPrincipalColaboradores.getValueAt(linha, 0).toString());
        String nome = (String) tabelaPrincipalColaboradores.getValueAt(linha, 1);
        String telefone = (String) tabelaPrincipalColaboradores.getValueAt(linha, 2);
        
        excluir.setNomeColaboradores(nome);
        excluir.setTelefoneColaboradores(telefone);
        excluir.setIdColaboradores(id);

        try {
            tipoColaboradores.excluir(excluir);
            atualizarTabela();
        } catch (SQLException ex) {
            Logger.getLogger(TelaColaboradores.class.getName()).log(Level.SEVERE, null, ex);
        }

        limpaCampos();

    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        //esse objeto referencia a classe onde irá salvar
        ColaboradorDAO cadColaboradores = new ColaboradorDAO();
        //esse objeto pega os métodos gets e sets
        Colaborador cadastro = new Colaborador();

        cadastro.setNomeColaboradores(jtfNomeColaboradores.getText());
        cadastro.setTelefoneColaboradores(jtfTelefoneColaboradores.getText());
        
        if (jtfCodigoColaboradores.getText().equals("")) {

            try {
                cadColaboradores.Cadastrar(cadastro);
                atualizarTabela();
            } catch (SQLException ex) {
                Logger.getLogger(TelaColaboradores.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Colaborador cadastrado com sucesso!",
                    "Cadastro de Colaborador", //Cria caixa de texto após executada a ação.
                    JOptionPane.INFORMATION_MESSAGE); //vai pegar, tratar a exception.
        }else{
            cadastro.setIdColaboradores(jtfCodigoColaboradores.getText());
            try {
                cadColaboradores.alterar(cadastro);
                atualizarTabela();
            } catch (SQLException ex) {
                Logger.getLogger(TelaColaboradores.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Colaborador atualizado com sucesso!",
                    "Atualização de Colaborador", //Cria caixa de texto após executada a ação.
                    JOptionPane.INFORMATION_MESSAGE); //vai pegar, tratar a exception.
        }

       

        
        limpaCampos();
        
        
        


    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpaCampos();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void tabelaPrincipalColaboradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPrincipalColaboradoresMouseClicked
        
    }//GEN-LAST:event_tabelaPrincipalColaboradoresMouseClicked

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed


    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEditarMouseClicked

    private void jbEditarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEditarMouseReleased
        //obter a partir da tabela qual o objeto selecionado 
        
        int linha = tabelaPrincipalColaboradores.getSelectedRow();
        if(linha < 0 )
            return;
        
        String id = (String) tabelaPrincipalColaboradores.getValueAt(linha, 0);
        String nome = (String) tabelaPrincipalColaboradores.getValueAt(linha, 1);
        String telefone = (String) tabelaPrincipalColaboradores.getValueAt(linha, 2);
        
        
        jtfCodigoColaboradores.setText(id);
        jtfNomeColaboradores.setText(nome);
        jtfTelefoneColaboradores.setText(telefone);
    }//GEN-LAST:event_jbEditarMouseReleased

    public void limpaCampos() {
        jtfCodigoColaboradores.setText("");
        jtfNomeColaboradores.setText("");
        jtfTelefoneColaboradores.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvar;
    public static javax.swing.JTextField jtfCodigoColaboradores;
    public static javax.swing.JTextField jtfNomeColaboradores;
    public static javax.swing.JTextField jtfTelefoneColaboradores;
    public static javax.swing.JTable tabelaPrincipalColaboradores;
    // End of variables declaration//GEN-END:variables
}
