/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import models.Servico;
import dao.ServicoDAO;
import tabela.Tabela;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Victor
 */
public class TelaServicos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Servicos
     */
    public TelaServicos() throws SQLException {
        initComponents();
        ServicoDAO.listaServicos();
        atualizarTabela();
    }

    
       private void atualizarTabela() throws SQLException{
        Tabela modelo = ServicoDAO.obterTabela();
        
        tabelaPrincipalServicos.setModel(modelo);
        tabelaPrincipalServicos.getColumnModel().getColumn(0).setPreferredWidth(1);
        tabelaPrincipalServicos.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelaPrincipalServicos.getColumnModel().getColumn(2).setPreferredWidth(200);
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPrincipalServicos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfCodigoServico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfNomeServico = new javax.swing.JTextField();
        jtfValorServico = new javax.swing.JTextField();
        jbLimpar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Cadastro de Serviços");

        tabelaPrincipalServicos.setBackground(new java.awt.Color(255, 204, 255));
        tabelaPrincipalServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome Serviço", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPrincipalServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPrincipalServicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPrincipalServicos);

        jLabel1.setText("Código");

        jtfCodigoServico.setBackground(new java.awt.Color(255, 204, 255));
        jtfCodigoServico.setForeground(new java.awt.Color(255, 204, 255));
        jtfCodigoServico.setToolTipText("");
        jtfCodigoServico.setEnabled(false);
        jtfCodigoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoServicoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome Serviço");

        jLabel3.setText("Valor");

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/8686254_ic_fluent_text_clear_formatting_icon.png"))); // NOI18N
        jbLimpar.setToolTipText("Limpar");
        jbLimpar.setBorderPainted(false);
        jbLimpar.setContentAreaFilled(false);
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/2639912_save_icon.png"))); // NOI18N
        jbSalvar.setToolTipText("Salvar");
        jbSalvar.setBorderPainted(false);
        jbSalvar.setContentAreaFilled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/2638315_bin_delete_dust_erace_garbage_icon.png"))); // NOI18N
        jbDeletar.setToolTipText("Excluir");
        jbDeletar.setBorderPainted(false);
        jbDeletar.setContentAreaFilled(false);
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/353430_checkbox_pen_edit_pencil_icon.png"))); // NOI18N
        jbEditar.setToolTipText("Editar");
        jbEditar.setBorderPainted(false);
        jbEditar.setContentAreaFilled(false);
        jbEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbEditarMouseReleased(evt);
            }
        });
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfValorServico)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCodigoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbDeletar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbSalvar)
                                .addGap(48, 48, 48)
                                .addComponent(jbEditar)))
                        .addGap(96, 96, 96)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfCodigoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfNomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfValorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbSalvar)
                            .addComponent(jbEditar))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbLimpar)
                            .addComponent(jbDeletar))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodigoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoServicoActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        ServicoDAO tipoPagamento = new ServicoDAO();
        //esse objeto pega os métodos gets e sets
        Servico excluir = new Servico();

        excluir.setNome(jtfNomeServico.getText());
        excluir.setValor(jtfNomeServico.getText());
        excluir.setIdServico(Integer.parseInt(jtfCodigoServico.getText()));

        try {
            tipoPagamento.excluir(excluir);
        } catch (SQLException ex) {
            Logger.getLogger(TelaServicos.class.getName()).log(Level.SEVERE, null, ex);
        }

        limpaCampos();

        try {
            ServicoDAO.listaServicos();
        } catch (SQLException ex) {
            Logger.getLogger(TelaServicos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        //esse objeto referencia a classe onde irá salvar
        ServicoDAO cadServicos = new ServicoDAO();
        //esse objeto pega os métodos gets e sets
        Servico cadastro = new Servico();

        cadastro.setNome(jtfNomeServico.getText());
        cadastro.setValor(jtfValorServico.getText());
        
        if (jtfCodigoServico.getText().equals("")) {

            try {
                cadServicos.Cadastrar(cadastro);
                atualizarTabela();
            } catch (SQLException ex) {
                Logger.getLogger(TelaColaboradores.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Serviço cadastrado com sucesso!",
                    "Cadastro de Serviço", //Cria caixa de texto após executada a ação.
                    JOptionPane.INFORMATION_MESSAGE); //vai pegar, tratar a exception.
        }else{
            cadastro.setIdServico(Integer.parseInt(jtfCodigoServico.getText()));
            try {
                cadServicos.alterar(cadastro);
                atualizarTabela();
            } catch (SQLException ex) {
                Logger.getLogger(TelaColaboradores.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Serviço atualizado com sucesso!",
                    "Atualização de Serviço", //Cria caixa de texto após executada a ação.
                    JOptionPane.INFORMATION_MESSAGE); //vai pegar, tratar a exception.
        }

       

        
        limpaCampos();
        
        
        

    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpaCampos();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void tabelaPrincipalServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPrincipalServicosMouseClicked
    }//GEN-LAST:event_tabelaPrincipalServicosMouseClicked

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbEditarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEditarMouseReleased
                int linha = tabelaPrincipalServicos.getSelectedRow();
        if(linha < 0 )
            return;
        
        String id = (String) tabelaPrincipalServicos.getValueAt(linha, 0);
        String nome = (String) tabelaPrincipalServicos.getValueAt(linha, 1);
        String telefone = (String) tabelaPrincipalServicos.getValueAt(linha, 2);
        
        
        jtfCodigoServico.setText(id);
        jtfNomeServico.setText(nome);
        jtfValorServico.setText(telefone);   
        
    }//GEN-LAST:event_jbEditarMouseReleased

    public void limpaCampos() {
        jtfCodigoServico.setText("");
        jtfNomeServico.setText("");
        jtfValorServico.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvar;
    public static javax.swing.JTextField jtfCodigoServico;
    public static javax.swing.JTextField jtfNomeServico;
    public static javax.swing.JTextField jtfValorServico;
    public static javax.swing.JTable tabelaPrincipalServicos;
    // End of variables declaration//GEN-END:variables
}
