/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.AtendimentoController;
import models.Atendimento;
import models.Cliente;
import models.Colaborador;
import models.Servico;
import dao.ServicoDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class TelaAtendimentos extends javax.swing.JInternalFrame {

    private AtendimentoController atendimentoController;

    public TelaAtendimentos() throws SQLException {
        initComponents();
        atendimentoController = new AtendimentoController();
        carregarCombos();
        atualizarTabela();
    }

    private void carregarCombos() throws SQLException {
        // Carrega serviços
        List<Servico> servicos = atendimentoController.listarServicos();
        DefaultComboBoxModel<Servico> modelServicos = new DefaultComboBoxModel<>();
        for (Servico servico : servicos) {
            modelServicos.addElement(servico);
        }
        cbxServico.setModel(modelServicos);

        // Carrega clientes
        List<Cliente> clientes = atendimentoController.listarClientes();
        DefaultComboBoxModel<Cliente> modelClientes = new DefaultComboBoxModel<>();
        for (Cliente cliente : clientes) {
            modelClientes.addElement(cliente);
        }
        cbxCliente.setModel(modelClientes);

        // Carrega colaboradores
        List<Colaborador> colaboradores = atendimentoController.listarColaboradores();
        DefaultComboBoxModel<Colaborador> modelColaboradores = new DefaultComboBoxModel<>();
        for (Colaborador colaborador : colaboradores) {
            modelColaboradores.addElement(colaborador);
        }
        cbxColaborador.setModel(modelColaboradores);
    }

    private void atualizarTabela() throws SQLException {
        List<Atendimento> atendimentos = atendimentoController.listarTodos();

        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Código", "Serviço", "Cliente", "Colaborador", "Data"}, 0
        );

        for (Atendimento atendimento : atendimentos) {
            String nomeServico = obterNomeServico(atendimento.getIdServico());
            String nomeCliente = obterNomeCliente(atendimento.getIdClientes());
            String nomeColaborador = obterNomeColaborador(atendimento.getIdColaboradores());

            model.addRow(new Object[]{
                atendimento.getIdAtendimentos(),
                nomeServico,
                nomeCliente,
                nomeColaborador,
                atendimento.getDataAtendimentos()
            });
        }

        tabelaPrincipalAtendimentos.setModel(model);
    }

    private String obterNomeServico(int idServico) throws SQLException {
        List<Servico> servicos = atendimentoController.listarServicos();
        for (Servico servico : servicos) {
            if (servico.getIdServico() == idServico) {
                return servico.getNome();
            }
        }
        return "";
    }

    private String obterNomeCliente(int idCliente) throws SQLException {
        List<Cliente> clientes = atendimentoController.listarClientes();
        for (Cliente cliente : clientes) {
            if (cliente.getIdCliente() == idCliente) {
                return cliente.getNome();
            }
        }
        return "";
    }

    private String obterNomeColaborador(int idColaborador) throws SQLException {
        List<Colaborador> colaboradores = atendimentoController.listarColaboradores();
        for (Colaborador colaborador : colaboradores) {
            if (colaborador.getIdColaboradores() == idColaborador) {
                return colaborador.getNome();
            }
        }
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPrincipalAtendimentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfCodigoAtendimentos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbLimpar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        cbxServico = new javax.swing.JComboBox();
        cbxCliente = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbxColaborador = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        spnDataAtendimento = new javax.swing.JSpinner();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Cadastro de Atendimentos");

        tabelaPrincipalAtendimentos.setBackground(new java.awt.Color(255, 204, 255));
        tabelaPrincipalAtendimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPrincipalAtendimentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPrincipalAtendimentos);

        jLabel1.setText("Código");

        jtfCodigoAtendimentos.setBackground(new java.awt.Color(255, 204, 255));
        jtfCodigoAtendimentos.setForeground(new java.awt.Color(255, 204, 255));
        jtfCodigoAtendimentos.setToolTipText("");
        jtfCodigoAtendimentos.setEnabled(false);
        jtfCodigoAtendimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoAtendimentosActionPerformed(evt);
            }
        });

        jLabel2.setText("Serviço");

        jLabel3.setText("Cliente");

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/8686254_ic_fluent_text_clear_formatting_icon.png"))); // NOI18N
        jbLimpar.setToolTipText("Limpar");
        jbLimpar.setBorderPainted(false);
        jbLimpar.setContentAreaFilled(false);
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/2639912_save_icon.png"))); // NOI18N
        jbSalvar.setToolTipText("Salvar");
        jbSalvar.setBorderPainted(false);
        jbSalvar.setContentAreaFilled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/2638315_bin_delete_dust_erace_garbage_icon.png"))); // NOI18N
        jbDeletar.setToolTipText("Excluir");
        jbDeletar.setBorderPainted(false);
        jbDeletar.setContentAreaFilled(false);
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/353430_checkbox_pen_edit_pencil_icon.png"))); // NOI18N
        jbEditar.setToolTipText("Editar");
        jbEditar.setBorderPainted(false);
        jbEditar.setContentAreaFilled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jLabel4.setText("Data Atendimento");

        jLabel5.setText("Colaborador");

        spnDataAtendimento.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.WEEK_OF_MONTH));
        spnDataAtendimento.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnDataAtendimento))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCodigoAtendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxServico, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbDeletar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbSalvar)
                                .addGap(48, 48, 48)
                                .addComponent(jbEditar)))
                        .addGap(96, 96, 96)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfCodigoAtendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbSalvar)
                            .addComponent(jbEditar))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbLimpar)
                            .addComponent(jbDeletar))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnDataAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodigoAtendimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoAtendimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoAtendimentosActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        if (jtfCodigoAtendimentos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione um atendimento para excluir",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            atendimentoController.excluir(jtfCodigoAtendimentos.getText());
            JOptionPane.showMessageDialog(this, "Atendimento excluído com sucesso!",
                    "Exclusão", JOptionPane.INFORMATION_MESSAGE);

            limpaCampos();
            atualizarTabela();

        } catch (SQLException ex) {
            Logger.getLogger(TelaAtendimentos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao excluir atendimento", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            // Obtém os IDs selecionados nos combos
            Servico servicoSelecionado = (Servico) cbxServico.getSelectedItem();
            Cliente clienteSelecionado = (Cliente) cbxCliente.getSelectedItem();
            Colaborador colaboradorSelecionado = (Colaborador) cbxColaborador.getSelectedItem();

            if (servicoSelecionado == null || clienteSelecionado == null || colaboradorSelecionado == null) {
                JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios",
                        "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // ✅ Obtém a data do SPINNER (NOVO)
            java.util.Date dataSelecionada = (java.util.Date) spnDataAtendimento.getValue();
            String dataFormatada = new java.text.SimpleDateFormat("yyyy-MM-dd").format(dataSelecionada);

            boolean sucesso = atendimentoController.salvar(
                    String.valueOf(servicoSelecionado.getIdServico()),
                    String.valueOf(clienteSelecionado.getIdCliente()),
                    String.valueOf(colaboradorSelecionado.getIdColaboradores()),
                    dataFormatada, // ✅ Data do spinner formatada
                    jtfCodigoAtendimentos.getText()
            );

            if (sucesso) {
                String mensagem = jtfCodigoAtendimentos.getText().isEmpty()
                        ? "Atendimento cadastrado com sucesso!" : "Atendimento atualizado com sucesso!";

                JOptionPane.showMessageDialog(this, mensagem, "Cadastro de Atendimentos",
                        JOptionPane.INFORMATION_MESSAGE);

                limpaCampos();
                atualizarTabela();
            }

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de Validação",
                    JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAtendimentos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao salvar atendimento", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpaCampos();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void tabelaPrincipalAtendimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPrincipalAtendimentosMouseClicked
        carregarAtendimentoDaTabela();
    }//GEN-LAST:event_tabelaPrincipalAtendimentosMouseClicked

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        carregarAtendimentoDaTabela();
    }//GEN-LAST:event_jbEditarActionPerformed

    private void carregarAtendimentoDaTabela() {
        int linha = tabelaPrincipalAtendimentos.getSelectedRow();
        if (linha < 0) {
            return;
        }

        try {
            String id = tabelaPrincipalAtendimentos.getValueAt(linha, 0).toString();
            Atendimento atendimento = atendimentoController.buscarPorId(id);

            if (atendimento != null) {
                jtfCodigoAtendimentos.setText(String.valueOf(atendimento.getIdAtendimentos()));

                // ✅ Define a data no SPINNER (NOVO)
                try {
                    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
                    java.util.Date data = sdf.parse(atendimento.getDataAtendimentos());
                    spnDataAtendimento.setValue(data);
                } catch (java.text.ParseException e) {
                    spnDataAtendimento.setValue(new java.util.Date()); // data atual como fallback
                }

                // Seleciona os itens nos combos baseado nos IDs
                selecionarComboPorId(cbxServico, atendimento.getIdServico());
                selecionarComboPorId(cbxCliente, atendimento.getIdClientes());
                selecionarComboPorId(cbxColaborador, atendimento.getIdColaboradores());
            }

        } catch (SQLException ex) {
            Logger.getLogger(TelaAtendimentos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao carregar atendimento", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void selecionarComboPorId(javax.swing.JComboBox comboBox, int id) {
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            Object item = comboBox.getItemAt(i);
            if (item instanceof Servico && ((Servico) item).getIdServico() == id) {
                comboBox.setSelectedIndex(i);
                return;
            }
            if (item instanceof Cliente && ((Cliente) item).getIdCliente() == id) {
                comboBox.setSelectedIndex(i);
                return;
            }
            if (item instanceof Colaborador && ((Colaborador) item).getIdColaboradores() == id) {
                comboBox.setSelectedIndex(i);
                return;
            }
        }
    }

    public void limpaCampos() {
        jtfCodigoAtendimentos.setText("");
        spnDataAtendimento.setValue(new java.util.Date()); // ✅ Define data atual
        // Opcional: resetar combos para primeira posição
        if (cbxServico.getItemCount() > 0) {
            cbxServico.setSelectedIndex(0);
        }
        if (cbxCliente.getItemCount() > 0) {
            cbxCliente.setSelectedIndex(0);
        }
        if (cbxColaborador.getItemCount() > 0) {
            cbxColaborador.setSelectedIndex(0);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxCliente;
    public static javax.swing.JComboBox cbxColaborador;
    private javax.swing.JComboBox cbxServico;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvar;
    public static javax.swing.JTextField jtfCodigoAtendimentos;
    private javax.swing.JSpinner spnDataAtendimento;
    public static javax.swing.JTable tabelaPrincipalAtendimentos;
    // End of variables declaration//GEN-END:variables
}
