/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.ClienteController;
import models.Cliente;
import dao.ClienteDAO;
import util.Tabela;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.TabelaUtils;

/**
 *
 * @author Victor
 */
public class TelaClientes extends javax.swing.JInternalFrame {

    ClienteController clienteController;

    /**
     * Creates new form Servicos
     */
    public TelaClientes() throws SQLException {
        initComponents();
        clienteController = new ClienteController();
        atualizarTabela();
    }

    private void atualizarTabela() throws SQLException {
        // Obtem lista de clientes
        List<Cliente> clientes = clienteController.listarTodos();

        // Popula tabela
        Tabela modelo = TabelaUtils.criarTabelaClientes(clientes);

        tabelaPrincipalClientes.setModel(modelo);
        tabelaPrincipalClientes.getColumnModel().getColumn(0).setPreferredWidth(1);
        tabelaPrincipalClientes.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelaPrincipalClientes.getColumnModel().getColumn(2).setPreferredWidth(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPrincipalClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfCodigoClientes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfNomeClientes = new javax.swing.JTextField();
        jtfTelefoneClientes = new javax.swing.JTextField();
        jbLimpar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Cadastro de Clientes");

        tabelaPrincipalClientes.setBackground(new java.awt.Color(255, 204, 255));
        tabelaPrincipalClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome Cliente", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPrincipalClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPrincipalClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPrincipalClientes);

        jLabel1.setText("Código");

        jtfCodigoClientes.setBackground(new java.awt.Color(255, 204, 255));
        jtfCodigoClientes.setForeground(new java.awt.Color(255, 204, 255));
        jtfCodigoClientes.setToolTipText("");
        jtfCodigoClientes.setEnabled(false);
        jtfCodigoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoClientesActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome");

        jLabel3.setText("Telefone");

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/8686254_ic_fluent_text_clear_formatting_icon.png"))); // NOI18N
        jbLimpar.setToolTipText("Limpar");
        jbLimpar.setBorderPainted(false);
        jbLimpar.setContentAreaFilled(false);
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/2639912_save_icon.png"))); // NOI18N
        jbSalvar.setToolTipText("Salvar");
        jbSalvar.setBorderPainted(false);
        jbSalvar.setContentAreaFilled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/2638315_bin_delete_dust_erace_garbage_icon.png"))); // NOI18N
        jbDeletar.setToolTipText("Excluir");
        jbDeletar.setBorderPainted(false);
        jbDeletar.setContentAreaFilled(false);
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/353430_checkbox_pen_edit_pencil_icon.png"))); // NOI18N
        jbEditar.setToolTipText("Editar");
        jbEditar.setBorderPainted(false);
        jbEditar.setContentAreaFilled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfCodigoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNomeClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(jtfTelefoneClientes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbDeletar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbSalvar)
                                .addGap(48, 48, 48)
                                .addComponent(jbEditar)))
                        .addGap(96, 96, 96)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfCodigoClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfNomeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfTelefoneClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbSalvar)
                            .addComponent(jbEditar))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbLimpar)
                            .addComponent(jbDeletar))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodigoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoClientesActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        if (jtfCodigoClientes.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente para excluir",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            clienteController.excluir(jtfCodigoClientes.getText());
            JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso!",
                    "Exclusão", JOptionPane.INFORMATION_MESSAGE);

            limpaCampos();
            atualizarTabela();

        } catch (SQLException ex) {
            Logger.getLogger(TelaClientes.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao excluir cliente", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            boolean sucesso = clienteController.salvar(
                    jtfNomeClientes.getText(),
                    jtfTelefoneClientes.getText(),
                    jtfCodigoClientes.getText()
            );

            if (sucesso) {
                String mensagem = jtfCodigoClientes.getText().isEmpty()
                        ? "Cliente cadastrado com sucesso!" : "Cliente atualizado com sucesso!";

                JOptionPane.showMessageDialog(this, mensagem, "Cadastro de Clientes",
                        JOptionPane.INFORMATION_MESSAGE);

                limpaCampos();
                atualizarTabela();
            }

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de Validação",
                    JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(TelaClientes.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao salvar cliente", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpaCampos();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void tabelaPrincipalClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPrincipalClientesMouseClicked
        carregarClienteDaTabela();
    }//GEN-LAST:event_tabelaPrincipalClientesMouseClicked

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        carregarClienteDaTabela();
    }//GEN-LAST:event_jbEditarActionPerformed

    private void carregarClienteDaTabela() {
        int linha = tabelaPrincipalClientes.getSelectedRow();
        if (linha < 0) {
            return;
        }

        String id = tabelaPrincipalClientes.getValueAt(linha, 0).toString();
        String nome = tabelaPrincipalClientes.getValueAt(linha, 1).toString();
        String telefone = tabelaPrincipalClientes.getValueAt(linha, 2).toString();

        jtfCodigoClientes.setText(id);
        jtfNomeClientes.setText(nome);
        jtfTelefoneClientes.setText(telefone);
    }

    public void limpaCampos() {
        jtfCodigoClientes.setText("");
        jtfNomeClientes.setText("");
        jtfTelefoneClientes.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvar;
    public static javax.swing.JTextField jtfCodigoClientes;
    public static javax.swing.JTextField jtfNomeClientes;
    public static javax.swing.JTextField jtfTelefoneClientes;
    public static javax.swing.JTable tabelaPrincipalClientes;
    // End of variables declaration//GEN-END:variables
}
